<?php
namespace Application\Entities;

/** @Entity @Table(name="payment_account") */
class Account 
{
  /** @Id @Column(type="integer") @AutoGenerated */
  protected $idaccount;

  /**
   * @ManyToOne(targetEntity="Application\Entities\User")
   * @JoinColumn(name="idusr", referencedColumnName="idusr")
   **/
  private $user;
  public function getUser() { return $this->user; }

  /** @Column(type="string") */
  protected $account_name;
  public function getAccountName() { return $this->account_name; }

  /** @Column(type="string") */
  protected $institution;

  /** @Column(type="datetime") */
  protected $created;

  /** @Column(type="boolean") */
  protected $deleted;

}