<?php
namespace Application\Entities;

/** @Entity @Table(name="payment_account") 
 * @InheritanceType("JOINED")
 * @DiscriminatorColumn(name="type", type="string")
 * @DiscriminatorMap({"bank" = "BankAccount", "credit_card" = "CreditCard", "loan" = "Loan"})
 */
class Account 
{
  /** @Id @Column(type="integer") @AutoGenerated */
  protected $idaccount;

  /**
   * @ManyToOne(targetEntity="Application\Entities\User")
   * @JoinColumn(name="idusr", referencedColumnName="idusr")
   **/
  private $user;
  public function getUser() { return $this->user; }

  /** @Column(type="string") */
  protected $account_name;
  public function getAccountName() { return $this->account_name; }

  /** @Column(type="string") */
  protected $institution;

  /** @Column(type="datetime") */
  protected $created;

  /** @Column(type="boolean") */
  protected $deleted;

  /**
   * @OneToMany(targetEntity="Balance", mappedBy="idaccount")
   **/
  protected $balances;

  public function __construct() {
    $this->balances = new \Doctrine\Common\Collections\ArrayCollection();
  }

}

/** @Entity @Table(name="payment_account_bank") */
class BankAccount extends Account {

  /** @Column(type="float") */
  protected $interest_rate;

  /** @Column(type="float") */
  protected $account_fee;

  /** @Column(type="string") */
  protected $account_fee_type;

}

/** @Entity @Table(name="payment_account_credit_card") */
class CreditCard extends Account {

}

/** @Entity @Table(name="payment_account_loan") */
class Loan extends Account {

}

/** @Entity @Table(name="payment_account_balance") */
class Balance {

  /** @Id @Column(type="integer") @AutoGenerated */
  protected $idaccount_balance;

  /**
   * @ManyToOne(targetEntity="Account", inversedBy="balances")
   * @JoinColumn(name="idaccount", referencedColumnName="idaccount")
   **/
  private $account;  
}