<?php
namespace Application\

/** @Entity @Table(name="payment") */
class Payment 
{
  /** @Id @Column(type="integer") @AutoGenerated */
  $idpayment;

  /** @Column(type="text") */
  $recurring;

}