<?php
namespace Application\Entities;

/** @Entity @Table(name="payment") */
class Payment 
{
  /** @Id @Column(type="integer") @AutoGenerated */
  protected $idpayment;

  /** @Column(type="text") */
  protected $recurring;

  /**
   * @ManyToOne(targetEntity="Application\Entities\User")
   * @JoinColumn(name="idusr", referencedColumnName="idusr")
   **/
  private $user;
  public function getUser() { return $this->user; }

  /**
   * @ManyToOne(targetEntity="Application\Entities\Account")
   * @JoinColumn(name="idaccount", referencedColumnName="idaccount")
   **/
  private $account;
  public function getAccount() { return $this->account; }

  /** @Column(type="integer") */
  protected $amount;

  /** @Column(type="text") */
  protected $description;

  /** @Column(type="datetime") */
  protected $created;

  /** @Column(type="boolean") */
  protected $deleted;

  public function __construct() {

  }
}