<?php echo $this->doctype(); ?>
<html>
  <head>
    <?php echo $this->headTitle(); ?> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <style type="text/css"> body { padding-top:60px; } </style> 
<?php 
   echo $this->headLink()
   ->appendStylesheet('/css/bootstrap.css')
   ->appendStylesheet('/css/bootstrap-responsive.css')
   ->appendStylesheet('/css/main.css')
   ->headLink(); 
?> 
    <?php echo $this->headScript(); ?> 

  </head>
<body>

<?php if(Zend_Auth::getInstance()->hasIdentity()) { 
  $isAuth = true;
  $auth = Zend_Auth::getInstance()->getIdentity();
} else {
   $isAuth = false;
}
?>


<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">Stay in the Black</a>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <?php echo $isAuth ? $auth->real_name : 'Login'; ?>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
   <?php if($isAuth) { ?>
              <li><a href="#">Profile</a></li>
              <li class="divider"></li>
              <li><a href="auth/logout">Sign Out</a></li>
                 <?php } else { ?>
<li><?php echo $this->loginForm; ?></li>
               <?php } ?>
            </ul>
          </div>

          <div class="nav-collapse">
            <ul class="nav">
   <?php if($isAuth) { ?>
              <li><a href="accounts">Accounts</a></li>
              <li><a href="accounts/setup">Setup</a></li>
               <?php } ?>
            </ul>
          </div>
        </div>
      </div>
</div>

<div class="container">
<?php echo $this->layout()->content; ?>
</div>

<?php 
$this->headScript()
                 ->appendFile("/js/jquery-1.7.2.min.js")
                 ->appendFile("/js/bootstrap-transition.js")
                 ->appendFile("/js/bootstrap-alert.js")
                 ->appendFile("/js/bootstrap-modal.js")
                 ->appendFile("/js/bootstrap-dropdown.js")
                 ->appendFile("/js/bootstrap-scrollspy.js")
                 ->appendFile("/js/bootstrap-tab.js")
                 ->appendFile("/js/bootstrap-tooltip.js")
                 ->appendFile("/js/bootstrap-popover.js")
                 ->appendFile("/js/bootstrap-button.js")
                 ->appendFile("/js/bootstrap-collapse.js")
                 ->appendFile("/js/bootstrap-carousel.js")
                 ->appendFile("/js/bootstrap-typeahead.js");

                 echo $this->headScript();
?>

<body>
</html>